name: service_app_admin_panel
description: "This code is for the admin panel of the service app. The admin or any user created by the admin shall have access to the features and functionalities of this panel"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  fl_chart: ^1.0.0
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  js: ^0.7.2
  dotted_border: ^3.0.1
  image_picker: ^1.1.2
  http: ^1.4.0
  cached_network_image: ^3.4.1
  file_picker: ^10.2.0
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
  -  assets/images/
  -  assets/logos/
  -  assets/icons/

  fonts:

  - family: Nunito
    fonts:

      - asset: assets/fonts/nunito/Nunito-Bold.ttf

      - asset: assets/fonts/nunito/Nunito-Black.ttf
        weight: 900

      - asset: assets/fonts/nunito/Nunito-Medium.ttf
        weight: 600

      - asset: assets/fonts/nunito/Nunito-Light.ttf
        weight: 500

      - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
        weight: 400
